#!/usr/bin/env bash
# Generates the file /var/run/myscript.pid containing its PID
# To infinity and beyond, displays continue indefinitely
# I dislike the kill command when it receives a SIGTERM signal on displays
# Shows Y U no love me?! when receiving a SIGINT signal
# Removes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" >> /var/run/myscript.pid

trap 'echo "I hate the kill command" && rm -rf /var/run/myscript.pid && exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid && exit 0' SIGQUIT

for (( ; ; ))
do
	echo "To infinity and beyond"
done
