#!/usr/bin/env bash
# Permanently writes I am alive! to the file /tmp/my_process
# Between each I am alive! message, the program should pause for 2 seconds

for (( ; ; ))
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
